sasmproject/settings.py, secrets.json, users/views.py
구글 했다가 안되고, 네이버 했다가 안돼서 결국 daum 으로....
=> daum smtp로 변경

stories/views.py
=> fixed cookie issue

users/views/base_view.py
=> login error 수정

places/serializers.py, places/views.py, users/views/base_view.py
=> [master] fix placedetail bug

users/views/base_view.py
=> [master] : "add access token code"

places/serializers.py, places/views.py, sasmproject/settings.py, users/views/base_view.py
resolved: #49
settings.py 에서 default authentication을 tokenauthentication으로 변경한다.
그러면 자동으로 django에서 authentication header에서 token 정보를 찾아 이를 request.user에 반영한다.
=> [master] fix : "change to tokenauthentication"

places/views.py
#54 remove placelikeserializer import
=> master : "remove placelikeserializer"

places/urls.py, places/views.py
=> master : "separate place detail and list"

places/views.py
=> master : "add filtering excpetion"

users/models.py, users/serializers.py, users/templates/users/password_reset.html, users/templates/users/user_activate_email.html, users/views/base_view.py, users/views/pw_change.py
=> master : "change html and signupview"

places/serializers.py, places/urls.py, places/views.py
=> master : "add map info"

stories/views.py
=> master : "fix story filter"

places/serializers.py, places/views.py, users/views/pw_change.py
=> master : "add placelike to placedetail"

sasmproject/settings.py, sasmproject/urls.py, sdp_admin/admin.py, sdp_admin/apps.py, sdp_admin/models.py, sdp_admin/tests.py, sdp_admin/urls.py, sdp_admin/views.py
=> Admin 페이지를 위한 sdp_admin 앱 생성 및 기본 설정

sdp_admin/serializers/places_serializers.py, sdp_admin/views/places_views.py
=> master : "add place name overlap check api and remove pagination in place admin"

places/serializers.py, places/views.py
serializer에 distance methodfield 추가 #131 resolved
=> master : "fix ordering by distance"

users/templates/users/password_reset.html, users/views/email_auth.py, users/views/pw_change.py
=> master : "change redirect url to sasm.co.kr"

users/views/base_view.py
=> master : check nickname overlap and reject email update

places/serializers.py, places/views/get_place_info.py
queryset을 values로 해서 넘겨줬더니 rep_pic의 값을 가져오는데 오류가 남.
values()에서 url의 값은 가져오지 못한다.
objects로 바꾸어 해결.
=> #158 fix : change queryset from values to objects

places/views/get_place_info.py
=> #207 fix : add self to function parameter

stories/serializers.py, stories/views.py
=> #190 refactor : "use separate serializers for swagger"

stories/urls.py, stories/views.py
Story list를 최신순, 오래된 순으로 정렬 및 카테고리별로 필터링
Resolves #251
=> #251 feat : order and filter story list

users/views/base_view.py
=> #257 fix : filter my story by category

stories/serializers.py
=> #190 feat : "return profile image and dates as comment info"

users/templates/users/password_reset.html, users/templates/users/user_activate_email.html
=> #265 fix : "cooridinate styles of email html template in mobile"

community/selectors.py, community/views.py, core/inspectors.py, sasmproject/settings/base.py
=> #261 chore : add community post api docs

community/selectors.py, community/views.py, core/inspectors.py, sasmproject/settings/base.py
=> #261 docs : add community post api docs

community/selectors.py, community/views.py
=> #261 feat : add additional fields in detail and list response

community/models.py, community/selectors.py, community/views.py
=> #261 feat : set hashtag list page size to 5

community/views.py
=> Revert "#261 feat : fix using requested data instead of validated data"

community/views.py
=> Revert "Revert "#261 feat : fix using requested data instead of validated data""

places/services.py, places/views/place_review_views.py
=> #298 fix : allow creating place review photos upto 3

users/views/views.py
=> #310 fix : fix nickname field to allow blank

community/selectors.py, community/views.py, places/selectors.py, places/views/place_review_views.py
1. 리팩토링 과정에서 삭제된 PlaceVisitorReviewListApi 'writer' 필드 반환
2. PostDetailApi 'id' 필드 반환
=> #298 feat : add extra serializer fields

users/views/views.py
- 유저가 작성한 스토리, 댓글 단 스토리를 조회하는 API에 대해 swagger docs 추가
=> #359 docs : add swagger docs for StoryGetApi

places/serializers.py
=> #358 feat : return additional info in place detail

places/serializers.py
=> #374 feat : return extra pic photos in place list

mypage/mixins.py, mypage/models.py, mypage/selectors/follow_selectors.py, mypage/services.py, mypage/urls.py, mypage/views/user_following.py
=> #382 feat : add search action to views and selectors

curations/selectors.py, curations/views.py
-CuratedStoryDetailApi에서 추가 정보 반환:
대표사진 3장, 프리뷰, 작성일, 작성자이메일, 닉네임, 프로필이미지
=> #350 feat : return extra fields in CuratedStoryDetailApi

curations/selectors.py, curations/urls.py, curations/views.py
-큐레이션 검색 기능을 위한 CurationListApi 추가
-검색범위: 큐레이션 제목/내용, 포함하는 스토리의 제목/장소명/장소카테고리/태그
=> #350 feat : add search curation function

stories/admin.py, stories/selectors.py, stories/services.py, stories/views.py
* StoryPhoto가 존재하지 않을 경우, extra_pics 추출 시 사용되는 split에서 에러나는 문제 해결 - Photo가 존재하는지 체크
* 이전에 생성된 스토리에 대해 맵 이미지가 존재하지 않을 경우 생성
* 스토리 리스트에서 작성자 profile 반환
=> #345 fix : fix extra pics and map image errors

curations/permissions.py, curations/selectors.py, curations/views.py
-profile_image, writer_nickname 반환
=> #350 feat : return writer info in CurationDetailApi

curations/selectors.py
=> #350 fix : list distinct stories in CuratedStoryDetail API

mypage/selectors/curations_selectors.py, mypage/urls.py, mypage/views/curations_views.py
- 내가 쓴 큐레이션
- 내가 좋아요 한 큐레이션(저장한)
- 검색된 큐레이션
=> #366 feat : add mypage curation APIs

stories/selectors.py
unintended deletion from https://github.com/sdp-tech/SASM_BE/pull/428
=> #424 fix : re-add deleted code

curations/views.py
=> #424 fix: match CurationLikeAPI with url

forest/selectors.py
=> #424 fix : CurationCommentList import bug fix

mypage/services.py, mypage/views/user_info_views.py, users/views/views.py
마이페이지 유저 정보 수정/ 유저 정보 get 시 자기소개 정보 추가
=> #467 feat : add introduction/user info change

curations/selectors.py, curations/views.py, forest/selectors.py, forest/views.py, stories/selectors.py, stories/views.py
실수로 기존 pr을 닫아 새로 올립니다 리뷰 부탁 드립니다.
=> #473 feat: add writer is followed

stories/selectors.py, stories/urls.py, stories/views.py
story/SamePlaceStory api
주어진 스토리와 같은 장소에 대한 스토리 리스트를 반환하는 api
=> feat: Same Place Include Story list API

curations/selectors.py, forest/selectors.py
커밋 변경하려던 중 실수로 기존 pr을 닫아 새로 pr 올립니다
=> #473 fix : modify writer_is_followed

curations/selectors.py, forest/selectors.py, stories/selectors.py
리스트 반환 시 writer_is_followed 정보는 필요 없기 때문에 그 경우 None 으로 되도록 함
=> fix : resolve forest list error

stories/selectors.py, stories/urls.py, stories/views.py
SamePlaceStory에 서브쿼리 사용
nickname, writer_is_verified, created, placename, title, extrapics, preview 정보 추가로 가져옴
=> #472 fix: Add SamePlaceStory informations

mypage/selectors/forest_selectors.py, mypage/views/forest_views.py
mypage/mypick_forest에서 태그의 수에 따라 리턴이 중복되는것을 제거하였습니다.
=> fix: Remove duplication at mypick_forest

mypage/selectors/forest_selectors.py, mypage/views/forest_views.py
마이페이지/내가 작성한 포레스트에서 해시태그 수에 따라 중복 반환되는 것 수정
=> #487 fix: Remove my_forest Duplication

curations/views.py
-web FE 작업 용이성을 위해 pagination을 10에서 8로 변경
=> fix : change CurationList pagination to 8

curations/selectors.py, curations/views.py
큐레이션 내부 스토리 디테일 조회 시에도 writer_is_followed 확인하도록 추가
=> feat : add writer follow to story detail

forest/selectors.py
=> #494 fix : modify preview length 100 to 150

mypage/selectors/forest_selectors.py, mypage/views/forest_views.py
mypage/mypick_forest
mypage/my_forest
return writer's nickname
=> fix: Add Nickname in Mypage/Forest

curations/selectors.py, curations/views.py
curations/admin_curaions/
curations/curation_search/
curations/verified_user_curations/
에서 user의 nickname이 반환되도록 수정
=> fix: Return NIckname at Curation List

stories/selectors.py, stories/views.py
stories/story_search에서
html_content의 앞 130자가 포함된  summary를 리턴
=> fix: Replace preview with Summary in Story Search

places/services.py, places/views/place_basic_views.py
장소 수정 시 rep_pic 필드가 포함되어 있지 않으면 기존 사진 파일을 그대로 업로드 하도록 수정.
=> #514 fix : modify place update api

places/selectors.py, places/urls.py, places/views/place_basic_views.py
places/check_address_overlap/
place_address에 대해 중복 확인을 하는 API
=> feat: Add Duplicate Check in Place Create by Address

curations/selectors.py, curations/views.py
curations/curation_search/
에서도 최신순 정렬이 가능하도록 구현
=> feat: Add Curation Order

curations/selectors.py, stories/views.py
stories/story_include_curation/
가 DateTime 필드를 추가로 반환하도록 수정
=> Add date at story include curation

curations/selectors.py, users/services.py, users/views/views.py
회원가입시 brithdate 필드를 받지 않도록 수정.
birthdate필드는 null로 들어갑니다.
=> fix: Delete Btirhdate Field in Signup

curations/selectors.py, curations/urls.py, curations/views.py
큐레이션, 포레스트, 스토리에 대한 통합검색
curations/total_search/
=> feat:Total Search for Curation, Forest, Story
